export { default as avatar } from "./img/Avatar.webp"
export { default as avatar_2 } from "./img/avatar.2.webp"
export { default as avatar2 } from "./img/avatar2.jpeg"
export { default as av3 } from "./img/av3.avif"
export { default as av4 } from "./img/av4.jpeg"

export { default as saig } from "./img/saig.png"
export { default as social } from "./img/social.png"
export { default as logging } from "./img/Spinner-1s-200px.svg"
export { default as logg } from "./img/Spinner.svg"

export { default as logo } from "./logo/socialHigh.png"
export { default as loggWhite } from "./logo/logo-white.png"
export { default as socialPng } from "./logo/social.png"
export { default as saigWhite } from "./logo/saig-white.png"
export { default as soc } from "./logo/soc.png"
export { default as saigWeb } from "./logo/saig.webp"
export { default as Pixel } from "./scren/pexels.jpg"
export { default as Screen } from "./scren/tg_image_1852626974.jpeg"
export { default as Screen2 } from "./scren/tg_image_1401892921.jpeg"
